PHP 8 Support
google/php-photoslibrary pull request #22
Opened 2020-12-27 12:38 UTC by eduardostuart

2020-12-27 12:39 UTC, eduardostuart commented
@googlebot I signed it!

2021-01-13 02:09 UTC, jfschmakeit requested changes
Thanks for preparing this!

Can you also confirm that all tests successfully pass on PHP 8?

2021-01-13 02:09 UTC, jfschmakeit commented on composer.json
> +    "php": "^5.5|^7.0|^8.0",
I believe we can simplify this to `>=5.5` at this point (similar to `goog/gax`.)

2021-03-09 20:58 UTC, ryihan requested changes
Change Update 8.0

2021-03-11 19:27 UTC, closed without merging

2021-07-18 21:57 UTC, skysphr commented
Why wasn't this merged?