Add support for PHP >= 7.4, PHPUnit 9, fix test errors
google/php-photoslibrary pull request #31
Opened 2021-09-03 14:18 UTC by bebetoalves

2021-09-03 14:19 UTC, bebetoalves commented
@googlebot I signed it!

2021-09-07 07:23 UTC, jfschmakeit requested changes
Thanks for this pull request!

Could you please rebase it onto the latest changes and reformat your files? We just merged a pull request that addressed some of your changes to the `FiltersBuilderTest.php` file. 

Otherwise this looks good, including bumping the minimum PHP version to 7.3+ and 8.0+, plus updating the phpunit dependency.

2021-09-07 07:23 UTC, jfschmakeit commented on phpunit.xml.dist
>  <?xml version="1.0" encoding="UTF-8"?>
Please reformat this file to follow the existing formatting style.

2021-09-22 01:01 UTC, jfschmakeit commented
@bebetoalves - We would like to merge this in and include this in the next release. It would be great if you could rebase your change and take a a look at the comment I added. Appreciate your help!

2021-09-28 07:09 UTC, jfschmakeit commented on phpunit.xml.dist
>  <?xml version="1.0" encoding="UTF-8"?>
We'll reformat this file in a follow up change.

2021-09-28 07:10 UTC, jfschmakeit commented
Let's merge this pull request in and I will follow up on the formatting comment afterwards.

Thanks for submitting this pull request!

2021-09-28 07:10 UTC, merged